### ISSUE TITLE
Week 4 ready for review

### ISSUE THREAD

**Issue by ChampaineV** [ChampaineV/indieProject#2]
@pawaitemadisoncollege week 4 is complete

1. What were your key learning points/takeaways? Hibernate is very helpful in lessening the redundancy and lengthy code in writing SQL statements to get table values. I'm excited to keep using this framework in our work and projects. 
2. What challenged you? I kept getting NullPointerException when accessing my database until I realized I wrote my password incorrectly in the hibernate.xml file. Other than that, everything has been going well. 
3. What problems did you solve and what resources did you use to solve them? I looked through my logs to understand where the errors occurred and looked at online resources to see how others solved the problem.

**Comment by pawaitemadisoncollege** [comment]
Hi @ChampaineV! Having this first entity and dao implemented with hibernate in your indie project is a great start!

- [x] Should there be a transaction in this method to ensure the entity is actually committed to the database? https://github.com/ChampaineV/indieProject/blob/0c9c2b817e173618ea79b0d95b8952b9b70a93bb/src/main/java/edu/productivity/persistence/UserData.java#L51-L55
