### ISSUE TITLE
Peer review - Austin Mussey

### ISSUE THREAD

**Issue by amoose20** [ChampaineV/indieProject#4]
[Review1.md](https://github.com/ChampaineV/indieProject/files/9739648/Review1.md)

**Comment by amoose20** [comment]
# Design/Code Review 1

## Project: Task Organizer Application

### Developer: Leichow Chang

### Reviewer: Austin Mussey

|Item |Considerations| Comments/Suggestions|
|--------|---------|---|
|||Reviewer comments and suggestions go here. Each item should have *at least* one "kudos" and two suggestions for improvement|
|**Problem Statement**|1. Accurately describes project purpose<br> 2. Is professional and free of typos, slang, etc.<br> 3. Fully explains the problem and the solution<br> 4. Is understandable by the average person| Excellent concept. Professional and well-written statement. For consideration: Is the user going to be the one to input what work was completed? I think a few more details on the process of recording work completed would be helpful. |
|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use. <br>2. The order in which values are displayed are logical and easy to understand/use <br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens | Logical, easy to understand flow through the application. Problem statement is represented. For consideration: Perhaps some screens representing a user login and registration. An ERD may also be helpful. |
|**Data model/Database**|1. Everything on the screens and problem statement/flow is represented in the model <br> 2. There is at least one 1-to-many relationship.<br> 3. The model represents good database design <br>| Database design looks solid. One 1-to-many relationship exists. For consideration: is there any additional information that might need to be stored in the Task entity? Things like: estimated/actual length of time until task completed, difficulty of task perhaps. I think this might be interesting to track this information for each task. |
|**Code**|1. Proper Maven project structure is used<br> 2. a .gitignore file for IntelliJ Java projects has been implemented <br> 3. There is not any redundant or copy/paste code in the JSPs or classes<br> 4. Classes are appropriately-sized (no monster classes)<br> Property files are used appropriately: no hard-coded values <br> 5. Logging statements are used rather than System.out.println and printStackTrace.<br> 6. There are appropriate unit tests/code coverage. | .gitignore file has been implemented. JSP's and class sizes look good. Unit tests and logging statements all look properly implemented. Everything looks good! For consideration: Continue to maintain the controller, entities, and JSP's! |

**Comment by pawaitemadisoncollege** [comment]
Hi @amoose20 This review that shows you took time to inspect all aspects of the project. Thank you for being   thoughtful in your feedback!
